version: '3.7'

services:
  fastapi-template:
    container_name: fastapi-template
    build: .
    image: fastapi-template:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
  
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data