"""

Revision ID: 38f503a01e77
Revises: 
Create Date: 2023-03-06 23:29:06.998817

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38f503a01e77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_name_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_name_key", "user", ["name"])
    # ### end Alembic commands ###
