"""

Revision ID: 46e345730671
Revises: 38f503a01e77
Create Date: 2023-03-10 17:55:05.674421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46e345730671"
down_revision = "38f503a01e77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted")
    # ### end Alembic commands ###
