"""

Revision ID: 8b70fd3f48fa
Revises: 46e345730671
Create Date: 2023-03-10 20:36:38.173710

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b70fd3f48fa"
down_revision = "46e345730671"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user", sa.Column("update_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "update_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
